### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by opensourced-code** [glixzzy/blooket-wrapper#19]
When you try to go and use the token hack it gives me this error: 
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined`

**Comment by glixzzy** [comment]
works fine for me? 

```js
const Blooket = require('blooket')

const client = new Blooket();

(async () => {
    const login = await client.login('signupnuts123', 'Deeznuts123');

    const x = await client.addTokens(500, 300, login.name, login.cookie)

    console.log(x)
})();
```

**Comment by glixzzy** [comment]
works fine for me?

```js
const Blooket = require('blooket')

const client = new Blooket();

(async () => {
    const login = await client.login('asfa', 'adfsd');

    const x = await client.addTokens(5000, 300, login.name, login.cookie)

    console.log(x)
})();
```

**Comment by opensourced-code** [comment]
UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "authorization"

**Comment by opensourced-code** [comment]
I'll try it on glitch or vscode

**Comment by glixzzy** [comment]
> UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "authorization"

can you give me the whole error? I have a feeling you are using the wrong version. The new version is 2.0.1

**Comment by DuckDictatorship** [comment]
I'm getting a similar issue with the getHistories() command. Using the exact code in the documentation, I consistently get an error:
`(node:820) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/home/runner/BlooketGradingApparatus/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/BlooketGradingApparatus/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/runner/BlooketGradingApparatus/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`


Again, this is the exact code from the docs page except for me adding the account info.

**Comment by DuckDictatorship** [comment]
> Version 2.0.1 does not work anymore. Version 3.5 seems to work for me?

there's a version 3.5? NPM still says it's on 2.0.1

**Comment by glixzzy** [comment]
i'll check these errors thoroughly out in the weekend and update it to a newer version, thanks for informing me.
